### ISSUE TITLE
如果没有一个订阅，就是订阅数是0，订阅，然后取消订阅，再订阅，就无法出版了 。。

### ISSUE THREAD

**Issue by trigrass2** [JcZou/uMCN#1]
如果是订阅了几个，去消一个，再加，再取消，订阅数不位0的化，没问题。

rt_err_t mcn_publish(McnHub* hub, const void* data)

     /* invoke callback func */
    node = hub->link_head;

    while (node != NULL) {

----------------------------
link_head 这个变成了NULL

**Comment by JcZou** [comment]
谢谢，在最新的版本上已经修复了这个问题
