### ISSUE TITLE
运行 mcn_test 测试程序出错

### ISSUE THREAD

**Issue by luhuadong** [JcZou/uMCN#5]
在 qemu-vexpress-a9 和 stm32f767-st-nucle 两个 BSP 上添加 uMCN 软件包，开启 example，编译下载后运行 mcn_test 出现如下错误：

```bash
msh />mcn_test
Function[rt_mutex_take]: scheduler is not available
(0) assertion failed at function:rt_mutex_take, line number:921
```

**Comment by JcZou** [comment]
你好，该问题已经修复（请查看最新的commit）
问题的原因是最新的rtt上不能在critical section内部调用rt_malloc/rt_free
